apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: 526362561261.dkr.ecr.ap-south-1.amazonaws.com/profile-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/streamingapp"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: mern-app
spec:
  selector:
    app: profile-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP