apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.mongodb }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.images.mongodb.repository }}:{{ .Values.images.mongodb.tag }}"
          ports:
            - containerPort: 27017
          resources:
{{ toYaml .Values.resources.mongodb | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.services.mongodb.port }}
      targetPort: 27017
  type: ClusterIP
